//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_III_Natasa_Jevtic_Bojana_Backo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRecipe()
        {
            this.tblIngredients = new HashSet<tblIngredient>();
            this.tblShoppingLists = new HashSet<tblShoppingList>();
        }
    
        public int RecipeId { get; set; }
        public string RecipeName { get; set; }
        public string Type { get; set; }
        public int NumberOfPersons { get; set; }
        public string Author { get; set; }
        public string Description { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIngredient> tblIngredients { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblShoppingList> tblShoppingLists { get; set; }
    }
}
