//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_III_Natasa_Jevtic_Bojana_Backo
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUser
    {
        public int UserId { get; set; }
        public string NameAndSurname { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
